name: validate
version: 1.8.0
author: Mike Mitterer  <office@mikemitterer.at>
description: This class assists in validating method arguments
homepage: https://github.com/MikeMitterer/dart-validate

environment:
  sdk: ">=2.3.0 <3.0.0"

dev_dependencies:
  test: any
  grinder: any
  build_runner: any
  build_test: any
  build_web_compilers: any
  console_log_handler: ^1.1.6
